# Generated by Django 5.2.6 on 2025-10-17 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0004_alter_chatmessage_created_at_alter_chatmessage_role_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='chatmessage',
            name='chatbot_cha_session_24e989_idx',
        ),
        migrations.RemoveIndex(
            model_name='chatmessage',
            name='chatbot_cha_session_fb5c97_idx',
        ),
        migrations.RemoveIndex(
            model_name='chatsession',
            name='chatbot_cha_user_id_52c956_idx',
        ),
        migrations.RemoveIndex(
            model_name='chatsession',
            name='chatbot_cha_user_id_e9081e_idx',
        ),
        migrations.RemoveIndex(
            model_name='chatsession',
            name='chatbot_cha_user_id_31a7b1_idx',
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], max_length=10),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='learning_focus',
            field=models.CharField(choices=[('general', 'General English'), ('grammar', 'Grammar'), ('vocabulary', 'Vocabulary'), ('conversation', 'Conversation'), ('reading', 'Reading'), ('writing', 'Writing'), ('pronunciation', 'Pronunciation'), ('exam', 'Exam Preparation')], default='general', max_length=20),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='proficiency_level',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='intermediate', max_length=20),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='title',
            field=models.CharField(default='New Chat', max_length=255),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
