version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: e-center
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

  web:
    build: .
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py create_superuser --email admin@example.com --password admin123 || true &&
             gunicorn --bind 0.0.0.0:8000 config.wsgi:application"
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DEBUG=True
      - DATABASE_URL=postgres://postgres:postgres@db:5432/e-center
      - SECRET_KEY=your-secret-key-change-in-production
      - DJANGO_SETTINGS_MODULE=config.settings.production

volumes:
  postgres_data:
  static_volume:
  media_volume: