# Generated by Django 5.2.6 on 2025-10-01 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0002_turkmenenglishword_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videolesson',
            old_name='video_file',
            new_name='video_url',
        ),
    ]
