# Generated by Django 5.2.6 on 2025-10-01 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0003_rename_video_file_videolesson_video_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'db_table': 'category',
            },
        ),
        migrations.AlterModelOptions(
            name='grammar',
            options={'ordering': ['order', 'created_at'], 'verbose_name_plural': 'grammar_lessons'},
        ),
        migrations.RemoveField(
            model_name='grammar',
            name='level',
        ),
        migrations.AddField(
            model_name='grammar',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='grammar_lessons', to='center.category'),
            preserve_default=False,
        ),
    ]
