# Generated by Django 5.2.6 on 2025-10-16 08:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_add_performance_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='learning_focus',
            field=models.CharField(choices=[('general', 'General English'), ('grammar', 'Grammar'), ('vocabulary', 'Vocabulary'), ('conversation', 'Conversation'), ('reading', 'Reading'), ('writing', 'Writing'), ('pronunciation', 'Pronunciation'), ('exam', 'Exam Preparation')], db_index=True, default='general', max_length=20),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='proficiency_level',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], db_index=True, default='intermediate', max_length=20),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='title',
            field=models.CharField(db_index=True, default='New Chat', max_length=255),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['session', 'created_at'], name='chatbot_cha_session_24e989_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['session', 'role'], name='chatbot_cha_session_fb5c97_idx'),
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['user', '-updated_at'], name='chatbot_cha_user_id_52c956_idx'),
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['user', 'proficiency_level'], name='chatbot_cha_user_id_e9081e_idx'),
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['user', 'learning_focus'], name='chatbot_cha_user_id_31a7b1_idx'),
        ),
    ]
